stages:         
  load data:                                        
    cmd: python src/load_data.py --config=params.yaml        #there should be no space in between equal tp sign
    deps:                       # passing dependecies that this stage is depend on which file, like it depends on 
    - src/get_data.py           # python file and csv file data set
    - src/load_data.py
    - data_given/winequality.csv
    outs:
    - data/raw/winequality.csv

## This for creating stages for the the pipe line
## stage 1 and it has run after doing 'dvc repro' command. This will create the dvc.lock file. 
## All the depedencies that were mentioned, it is started tracking those as a code in this lock file.
## What ever changes i have done that will be tracked.

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/winequality.csv
    outs:
    - data/processed/train_winequality.csv
    - data/processed/test_winequality.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps: 
    - data/processed/train_winequality.csv
    - data/processed/test_winequality.csv
    - src/train_and_evaluate.py
    params:
    - estimators.ElasticNet.params.aplha  
    - estimators.ElasticNet.params.l1_ratio
    outs:
    - saved_models/model.joblib
