stages:
  load data:
    cmd: python src/load_data.py --config=params.yaml        #there should be no space in between equal tp sign
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/winequality.csv
    outs:
    - data/raw/winequality.csv